<?php

namespace App;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class AddBlockCommand extends ContainerAwareCommand {


    public function configure()
    {
        $this
            ->setName('mage-coin:add-block')
            ->setDescription('Add block to MageCoin block chain')
            ->addOption('data', null, InputOption::VALUE_REQUIRED, 'Data to be serialized in block', null)
            ->addOption('purge', null, InputOption::VALUE_OPTIONAL, 'Purge json files and import new version !', null);
}

    public function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }


}